env:
  browser: true
  es6: true
plugins:
parser: babel-eslint
extends:
  - 'eslint:recommended'
  - google
parserOptions:
  sourceType: module
rules:
  require-jsdoc:
    - off
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  arrow-parens:
    - 0
    - as-needed
  max-len:
    - 0
    - 160
    - 2
  comma-dangle:
    - 0
  no-invalid-this:
    - 0

