env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
  - google
parserOptions:
  sourceType: module
rules:
  require-jsdoc:
    - off
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
